version: '3.8'
services:
  spacemesh:
    # image: eth2dev/go-spacemesh:v1.3.2
    image: 'go-spacemesh'
    container_name: 'gosm'
    build:
      context: .
    networks:
      - gosm_network
    privileged: true
    volumes:
      - ${NODEDATA_DIR:-./node_data}:/app/go-spacemesh/node_data
      - ${POSTDATA_DIR:-./post_data}:/app/go-spacemesh/post_data
    environment:
      - TZ=Asia/Shanghai
      - SMESHING_COINBASE_ADDRESS=${SMESHING_COINBASE_ADDRESS:?please make sure to set your SMESHING_COINBASE_ADDRESS environment variable in the .env file}
      - FILE_SIZE=${FILE_SIZE:?please make sure to set your FILE_SIZE environment variable in the .env file}
      - NUMUNITS=${NUMUNITS:?please make sure to set your NUMUNITS environment variable in the .env file}
      - PROVIDER=${PROVIDER:?please make sure to set your PROVIDER environment variable in the .env file}
      - NONCES=${NONCES:?please make sure to set your NONCES environment variable in the .env file}
      - THREADS=${THREADS:?please make sure to set your THREADS environment variable in the .env file}
      - POST_MIN_WORKERS=${POST_MIN_WORKERS:?please make sure to set your POST_MIN_WORKERS environment variable in the .env file}
      - POST_WORKERS=${POST_WORKERS:?please make sure to set your POST_WORKERS environment variable in the .env file}
    restart: unless-stopped

networks:
  gosm_network: